import Head from 'next/head'
import Layout from "@/components/Layout"
import Image from 'next/image'
import Link from 'next/link'
import ProfilePic from "../../public/images/profile/adrianBW.png"
import Hero from '@/components/Hero'
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>adrianAYALA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className='pt-0'>
         <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={ProfilePic} alt="adrianBnW" className='w-full h-auto' />
            </div>
            {/* <section id="hero">
              <Hero />
            </section> */}
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Desire to See My Vision Transformed Reality With Code and Design." className='!text-5xl !text-left'/>
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas intro innovative web applications. Explore my latest projects and articles, showcasing my expertise in utilizing NextJS, TailWindCSS, and web development.
              </p>
            </div>
            <div className='flex items-center self-start mt-2'>
              <Link href="mailto:ayala.adrian@gmail.com" target={"_blank"}
              className="ml-4 text-lg font-medium capitalize text-dark underline"
              >Contact Me</Link>
            </div>
         </div>
        </Layout>
        
      </main>
    </>
  )
}
